import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[font]
size = 20

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[shell]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
{ key = "T", mods = "Command", action = "None" },
]
