# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
cmd-alt-h = 'focus left'
cmd-alt-j = 'focus down'
cmd-alt-k = 'focus up'
cmd-alt-l = 'focus right'

cmd-alt-shift-h = 'move left'
cmd-alt-shift-j = 'move down'
cmd-alt-shift-k = 'move up'
cmd-alt-shift-l = 'move right'

cmd-alt-b = 'split horizontal'
cmd-alt-v = 'split vertical'

cmd-alt-f = 'fullscreen'

cmd-alt-s = 'layout v_accordion' # 'layout stacking' in i3
cmd-alt-w = 'layout h_accordion' # 'layout tabbed' in i3
cmd-alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

cmd-alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide.html#floating-windows
#cmd-alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# cmd-alt-a = 'focus parent'

cmd-alt-1 = 'workspace 1'
cmd-alt-2 = 'workspace 2'
cmd-alt-3 = 'workspace 3'
cmd-alt-4 = 'workspace 4'
cmd-alt-5 = 'workspace 5'
cmd-alt-6 = 'workspace 6'
cmd-alt-7 = 'workspace 7'
cmd-alt-8 = 'workspace 8'
cmd-alt-9 = 'workspace 9'
cmd-alt-0 = 'workspace 10'

cmd-alt-shift-1 = 'move-node-to-workspace 1'
cmd-alt-shift-2 = 'move-node-to-workspace 2'
cmd-alt-shift-3 = 'move-node-to-workspace 3'
cmd-alt-shift-4 = 'move-node-to-workspace 4'
cmd-alt-shift-5 = 'move-node-to-workspace 5'
cmd-alt-shift-6 = 'move-node-to-workspace 6'
cmd-alt-shift-7 = 'move-node-to-workspace 7'
cmd-alt-shift-8 = 'move-node-to-workspace 8'
cmd-alt-shift-9 = 'move-node-to-workspace 9'
cmd-alt-shift-0 = 'move-node-to-workspace 10'

cmd-alt-shift-c = 'reload-config'

cmd-alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
